# Generated by Django 4.2.5 on 2023-09-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empregado', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
            ],
        ),
    ]
